# Generated by Django 4.1 on 2023-01-17 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_eventmodel_name'),
        ('tiket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventmodel'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
