# Generated by Django 4.1 on 2023-01-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventmodel_name'),
        ('tiket', '0002_ticketmodel_event_alter_ticketmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='event',
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.eventmodel'),
            preserve_default=False,
        ),
    ]
