# Generated by Django 4.1 on 2023-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0003_remove_ticketmodel_event_ticketmodel_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='city',
            field=models.TextField(default='city'),
        ),
    ]
