# Generated by Django 4.1 on 2022-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(default='s', max_length=40),
        ),
    ]
