# Generated by Django 4.1 on 2023-01-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebadge',
            name='topic',
            field=models.CharField(choices=[('event', 'event'), ('blog', 'blog'), ('topic', 'topic')], default='event', max_length=40),
        ),
    ]
