# Generated by Django 4.1 on 2023-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_badge', '0002_alter_homebadge_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebadge',
            name='slug',
            field=models.IntegerField(default=1),
        ),
    ]
