# Generated by Django 4.1 on 2023-01-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_badge', '0003_homebadge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebadge',
            name='slug',
            field=models.IntegerField(default=0),
        ),
    ]
